version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "8085:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8086:8086"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8086

networks:
  app-network:
